### ISSUE TITLE
KeepassXC CLI Check

### ISSUE THREAD

**Issue by defconxt** [lxbrvr/alfred-keepassxc-workflow#10]
On MacOS Ventura 13.1 I am unable to set the path manually to the cli executable. It opens up finder and then there isn't an option to "right click -> show contents" to dive deeper to locate it. I'm not seeing where I can add a path manually within the workflow.

Sorry if this is dumb, but I'm fairly new to Macs and maybe I'm missing something.

**Comment by lxbrvr** [comment]
Let me show you how I would do it

**The first way**

1. Enter `kp:settings` or enter `kp` and select "Settings"
2. Select "KeepassXC CLI path". It opens dialog window
3. In the opened dialog window you need to find your cli for keepassxc
4. Usually it show you all files and if you want to see file content then you need to right click on this file and select "Show in finder". And then you can select "Show contents".

**The second way**

Open the workflow in the Alfred and follow the steps below:

![image](https://user-images.githubusercontent.com/20011426/212264776-f8b909a8-afc5-4651-b371-218dac531d74.png)

![image](https://user-images.githubusercontent.com/20011426/212265044-aaaa2cb1-ec27-4900-ae3c-527c7f9b443f.png)

**Comment by lxbrvr** [comment]
In the opened dialog window if you can't see any system directory but your cli is there then press `Shift + Cmd + .`

**Comment by defconxt** [comment]
Oh sweet! I was able to actually do the first one but a bit different.


I selected “show in finder” and then took keepasscli and dragged it over to the window title bar and it mapped to it in the kp:settings prompt to change the path for the CLI.


Cheers!
