### ISSUE TITLE
password

### ISSUE THREAD

**Issue by ghost** [lxbrvr/alfred-keepassxc-workflow#11]
Hello, I forgot the password of the main data, but there is a password in the configuration, how can I check the original password?

**Comment by lxbrvr** [comment]
Hi! 

I see that you have already closed the issue, but just in case I will give you the answer.

Your password is stored in the "Keychain Access" application. To see your saved password, you need to do the following:

1. Open the "Keychain Access" application.
2. Enter "com.lxbrvr.keepassxcalfred" in the search box (top right).
3. Open the found item.
4. In the opened modal window click on "Show password".
5. It will ask you for your system password.

After you enter the system password, you will see the saved password.

**Comment by ghost** [comment]
thank you !
But I changed the computer, the password is gone.
