### ISSUE TITLE
FR: Direct insert to frontmost app

### ISSUE THREAD

**Issue by IOIO72** [lxbrvr/alfred-keepassxc-workflow#4]
Each attribute of one database entry should be insertable to the frontmost app by pressing the ⌘ key on the item.

**Comment by lxbrvr** [comment]
@IOIO72 

Looks useful. I've implemented this feature. It will be available In version 1.2.0.

**Comment by lxbrvr** [comment]
Available in [1.2.0](https://github.com/lxbrvr/alfred-keepassxc-workflow/releases/download/1.2.0/keepassxc-1.2.0.alfredworkflow)

**Comment by IOIO72** [comment]
Great! Thank you! :)
