### ISSUE TITLE
FR: Forget copied passwords

### ISSUE THREAD

**Issue by IOIO72** [lxbrvr/alfred-keepassxc-workflow#5]
For security reasons, copied passwords should be deleted from the clipboard.

* Forget copied password by timeout: X minutes. (-> Check in X minutes, if the content of the clipboard matches the last copied password and delete it. When choosing a password from another database within the X minutes erase timeout, check as well.)
* Forget copied password, when it was pasted one time.

**Comment by lxbrvr** [comment]
> Forget copied password by timeout: X minutes. (-> Check in X minutes, if the content of the clipboard matches the last copied password and delete it. When choosing a password from another database within the X minutes erase timeout, check as well.)

In progress.

> Forget copied password, when it was pasted one time.

Is it possible? 

Unfortunately, now I have no idea how to keep track of all the insertion options (cmd + v, mouse, etc.) and how to determine that this event happened and it is event we need.

**Comment by lxbrvr** [comment]
> Forget copied password by timeout...

Available in 2.2.0
