### ISSUE TITLE
macOS Monterey 12.3

### ISSUE THREAD

**Issue by det-box** [lxbrvr/alfred-keepassxc-workflow#6]
Hello,
unfortunately since Momterey 12.3 there is no
/usr/bin/python2
more.
`[15:22:51.084] ERROR: KeepassXC Alfred[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.617C5831-8989-4F31-9C3F-9479C459C6BE%3EF51F13EF-FFAE-46EB-A4E1-2282CE664D61)] Code 127: /Users/detlef/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/02A2EABE-EFC5-4CFF-BEAD-06425E923230: line 1: /usr/bin/python2: No such file or directory`

There is only
/usr/bin/python3

Please adjust.
Thanks

**Comment by kkrepocom** [comment]
我也遇到了同样的问题，麻烦修复一下，谢谢了

**Comment by lxbrvr** [comment]
I am preparing a new version of the workflow that will be able to work with python3.

**Comment by lxbrvr** [comment]
Done! Please use [the 2.0.0 version](https://github.com/lxbrvr/alfred-keepassxc-workflow/releases/download/2.0.0/keepassxc-2.0.0.alfredworkflow)

I'm going to close this issue. If you find some problems with the new version of the workflow, I suggest to consider them in new issues.
