### ISSUE TITLE
Not working in keepassxc version 2.7

### ISSUE THREAD

**Issue by wisinfun** [lxbrvr/alfred-keepassxc-workflow#7]

**Comment by lxbrvr** [comment]
In version 2.7, the KeepassXC team removed the `locate` command from their CLI, which is used to search for KeepassXC entries, and they added the `search` command as a replacement.

Thank you for reporting the problem. I'll prepare a new version that will work with KeepassXC 2.7.

**Comment by lxbrvr** [comment]
@wisinfun 

Done. Use [the 2.1.0 version](https://github.com/lxbrvr/alfred-keepassxc-workflow/releases/download/2.1.0/keepassxc-2.1.0.alfredworkflow). And please note that the search behavior now is the same as in the KeepassXC UI. For more information, see [here](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_searching_the_database).

**Comment by wisinfun** [comment]
> @wisinfun
> 
> Done. Use [the 2.1.0 version](https://github.com/lxbrvr/alfred-keepassxc-workflow/releases/download/2.1.0/keepassxc-2.1.0.alfredworkflow). And please note that the search behavior now is the same as in the KeepassXC UI. For more information, see [here](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_searching_the_database).

Thank you very much
