### ISSUE TITLE
Search Error

### ISSUE THREAD

**Issue by f-x1-1** [lxbrvr/alfred-keepassxc-workflow#8]
Keep showing the following errow when i try to search for something in the database.

`/usr/local/bin/keepassxc-cli not found. Select a correct KeepassXC CLI.`

**Comment by f-x1-1** [comment]
It says “keepassxc-cli not found” even though it’s installed. There is no keepassxc-cli in /usr/local/bin

Kind Regards

Fahad Zafar

**Comment by lxbrvr** [comment]
Please tell me the path specified in the workflow settings is the same as the path in `which keepassxc-cli` output?

If you can, send here the output of `which keepassxc-cli` command and `KeepassXC CLI path` in the workflow settings (enter `kp:settings` in Alfred and find that option).

**Comment by lxbrvr** [comment]
@f-x1-1 

Were you able to configure it? 
Is there anything else I can do to help you, or can we close this issue?
